### ISSUE TITLE
Some tests fails randomly

### ISSUE THREAD

**Issue by Amraneze** [Amraneze/spideo-challenge#1]
## Environment

| OS                |
| -------------------- |
| Windows home x64 |
| Ubuntu 18.04 |

## Steps to reproduce

1. Rerun AuctionHouseServiceTests multiple times
2. If nothing failed, keep going until one will fail

## Expected behavior

All the 16th test cases will pass

## Actual behavior

One of test is failing one time per 4 or 5

* Somtimes, the test case **itShouldListAllAuctionsOfAnAuctionHouse** is failing due the exception 
```
IndexOutOfBoundsException: Index: 4, Size: 4, AuctionHouseServiceTests.java:152
```
* Somtimes, the test case **itShouldBidOnAnAuction** is failing due the exception
```
bidding-price-is-low{400, Bidding price is low}, AuctionHouseService.java:124
```
*Somtimes, the test case **itShouldDeleteAnAuctionHouse** is failing due the exception 
```
ConcurrentModificationException, AuctionHouseRepositoryImpl.java:21
	at AuctionHouseRepositoryImpl.findAuctionHouseByName(AuctionHouseRepositoryImpl.java:21)
	at AuctionHouseService.createAuctionHouse(AuctionHouseService.java:29)
	at itShouldDeleteAnAuctionHouse$3(AuctionHouseServiceTests.java:91)
```

Maybe the best solution would be to redo the test cases so they will have multiple data instead of clearing the same db 🤕

**Comment by Amraneze** [comment]
I ran 20000 tests to check if we still get the exceptions but I could reproduce it anymore

![image](https://user-images.githubusercontent.com/28459763/68092837-911ebd00-fe8f-11e9-9207-ed579f4aa600.png)

![image](https://user-images.githubusercontent.com/28459763/68092840-9bd95200-fe8f-11e9-9a99-c3bd9186b9f7.png)
